### ISSUE TITLE
Can't dispatch patch release workflow

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/gha-action-ci#13]
Just like https://github.com/silverstripe/gha-ci/issues/145, gha-action-ci is failing to dispatch the patch release workflow.

In this case it's just the permission that's missing: https://github.com/silverstripe/gha-ci/actions/runs/10276180947/job/28436179485 returns a 403

## PRs
- https://github.com/silverstripe/gha-action-ci/pull/14
- https://github.com/silverstripe/gha-action-ci/pull/16
- https://github.com/silverstripe/module-standardiser/pull/69
- https://github.com/silverstripe/gha-action-ci/pull/15
- https://github.com/silverstripe/gha-auto-tag/pull/23
- https://github.com/silverstripe/gha-ci/pull/147
- https://github.com/silverstripe/gha-dispatch-ci/pull/19
- https://github.com/silverstripe/gha-generate-matrix/pull/102
- https://github.com/silverstripe/gha-issue/pull/15
- https://github.com/silverstripe/gha-keepalive/pull/17
- https://github.com/silverstripe/gha-merge-up/pull/43
- https://github.com/silverstripe/gha-pull-request/pull/17
- https://github.com/silverstripe/gha-run-tests/pull/36
- https://github.com/silverstripe/gha-tag-release/pull/28
- https://github.com/silverstripe/gha-trigger-ci/pull/11
- https://github.com/silverstripe/gha-update-js/pull/31

**Comment by emteknetnz** [comment]
Assigning back to Guy to confirm things work

**Comment by GuySartorelli** [comment]
All merged and everything seems to be working as expected now.
